##**First Step : Pandas**

Untuk dapat menggunakan library pandas pada python, perlu untuk mengimpor library tersebut dengan cara mengetikan sintaks berikut

<p align="center"><code><b>import pandas as pd</b></code></p>

lalu jalankan (<i>run</i>) program.

<br>docs : *https://pandas.pydata.org/docs/getting_started/install.html*

### 👨‍💻 Task 1

Ketikan kode `import pandas as pd` pada prompt dibawah ini lalu jalankan

In [14]:
# Write your code below here & exec!
import pandas as pd

# Atur agar semua kolom bisa ditampilkan
pd.set_option('display.max_columns', None)

## **Data Extraction**

* Dalam konteks data extraction, Pandas dapat digunakan untuk membaca data dari berbagai sumber, seperti file CSV, Excel, SQL database, dan lainnya, dan mengubahnya menjadi DataFrames untuk analisis lebih lanjut.

* Beberapa fungsi dan metode Pandas yang umum digunakan untuk data extraction adalah sebagai berikut:

<ul>
<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html">pd.read_csv()</a></code>: Digunakan untuk membaca data dari file CSV dan mengonversinya menjadi DataFrame.

<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_excel.html">pd.read_excel()</a></code>: Membaca data dari file Excel dan membuat DataFrame dari lembar kerja atau tabel tertentu.

<code><a href="https://pandas.pydata.org/docs/reference/api/pandas.read_sql.html">pd.read_sql()</a></code>: Mengambil data dari basis data SQL menggunakan SQL query dan menyimpannya dalam bentuk DataFrame.
</ul>

### 👨‍💻 Task 2

Data yang digunakan adalah data yang bersumber dari _cloud database_ : BigQuery yakni data transaksi pizza. Untuk itu perlu menghubungkan Google Colab dengan Google Cloud (khususnya BigQuery) dan melakukan autentikasi akun, sehingga data yang akan diolah bisa diekstrak dari database.

In [15]:
from google.colab import auth, data_table
from google.cloud import bigquery
from pandas_gbq import to_gbq

# Proses autentikasi akun
auth.authenticate_user()
print('Authenticated')

Authenticated

In [16]:
# Buat BigQuery client
project_id = 'fullstack-bangalore-494812'
client = bigquery.Client(project = project_id)

### 👨‍💻 Task 2.1

Lakukan proses ekstraksi data trx_order pada dataset pizza_transaction, lalu simpan hasilnya ke DataFrame yang diberi nama `orders`. Tampilkan datanya!

In [17]:
# Inisialisasi query yang akan dijalankan
query_order = """
  SELECT
    *
  FROM fullstack-bangalore-494812.pizza_transaction.trx_order
"""

# Proses ekstraksi data dari BigQuery ke pandas
orders = client.query(query_order).to_dataframe()

# Tampilkan hasil
display(orders.head())

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,created_date,updated_date
0,TRX000026,CUST006333,EMP000208,01/01/2025,14:54:26,15:23:02,0,None,2025-01-01 14:54:31,<NA>
1,TRX000037,CUST003319,EMP000208,01/01/2025,16:56:09,17:18:48,0,None,2025-01-01 16:56:14,<NA>
2,TRX000057,CUST008422,EMP000208,01/01/2025,19:10:51,19:30:38,0,None,2025-01-01 19:10:56,<NA>
3,TRX000077,CUST001979,EMP000208,01/02/2025,12:22:46,12:41:29,0,None,2025-01-02 12:22:51,<NA>
4,TRX000087,CUST004837,EMP000208,01/02/2025,14:01:02,14:29:46,0,None,2025-01-02 14:01:07,<NA>

### 👨‍💻 Task 2.2

Lakukan proses yang sama yakni ekstraksi data pada dataset pizza_transaction untuk data berikut:

* Ekstrak data `trx_order_detail` lalu simpan ke dataframe `order_details`
* Ekstrak data `mst_customer` lalu simpan ke dataframe `customers`
* Ekstrak data `mst_pizza` lalu simpan ke dataframe `pizzas`
* Ekstrak data `mst_pizza_type` lalu simpan ke dataframe `pizza_types`

In [18]:
# Inisialisasi query yang akan dijalankan -> Ekstrak data trx_order_detail
query_order_detail = """
  SELECT
    *
  FROM fullstack-bangalore-494812.pizza_transaction.trx_order_detail
"""

# Proses ekstraksi data dari BigQuery ke pandas
order_details = client.query(query_order_detail).to_dataframe()

# Tampilkan hasil
display(order_details.head())

,order_details_id,order_id,pizza_id,quantity,created_date,updated_date
0,TRXD000001,TRX000001,PIZZA_HAWAIIAN_M,1,2025-01-01 11:38:41,<NA>
1,TRXD000002,TRX000002,PIZZA_CLASSIC_DLX_M,1,2025-01-01 11:57:45,<NA>
2,TRXD000003,TRX000002,PIZZA_FIVE_CHEESE_L,1,2025-01-01 11:57:45,<NA>
3,TRXD000004,TRX000002,PIZZA_ITAL_SUPR_L,1,2025-01-01 11:57:45,<NA>
4,TRXD000005,TRX000002,PIZZA_MEXICANA_M,1,2025-01-01 11:57:45,<NA>

In [19]:
# Inisialisasi query yang akan dijalankan -> Ekstrak data mst_customer
query_customer = """
  SELECT
    *
  FROM fullstack-bangalore-494812.pizza_transaction.mst_customer
"""

# Proses ekstraksi data dari BigQuery ke pandas
customers = client.query(query_customer).to_dataframe()

# Tampilkan hasil
display(customers.head())

,customer_id,customer_name,gender,birth_date,phone_number,email,open_date,created_date,updated_date
0,CUST007150,Salsabila Purnawati,F,1990-09-17,081 074 0279,salsabila.purnawati@hotmail.com,2024/12/31,2024-12-31 18:55:01,<NA>
1,CUST003319,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,2024-12-31 17:24:59,<NA>
2,CUST007254,Elma Maryati,F,1984-03-25,+62-008-153-1104,elma.maryati@yahoo.com,2024/12/31,2024-12-31 00:48:10,<NA>
3,CUST004392,Najwa Natsir,F,1980-05-25,+62 (678) 311-9386,najwa.natsir@hotmail.com,2024/12/31,2024-12-31 17:41:05,<NA>
4,CUST005127,Hani Palastri,F,2003-02-10,+62 (368) 876-1503,hani.palastri@hotmail.com,2024/12/31,2024-12-31 18:37:35,<NA>

In [20]:
# Inisialisasi query yang akan dijalankan -> Ekstrak data mst_pizza
query_pizza = """
  SELECT
    *
  FROM fullstack-bangalore-494812.pizza_transaction.mst_pizza
"""

# Proses ekstraksi data dari BigQuery ke pandas
pizzas = client.query(query_pizza).to_dataframe()

# Tampilkan hasil
display(pizzas.head())

,pizza_id,pizza_type_id,size,price,production_cost,created_date,updated_date
0,PIZZA_PEPPERONI_L,PIZZA_TYPE_PEPPERONI,L,IDR123525,IDR96390,2024-12-31 00:00:00,<NA>
1,PIZZA_HAWAIIAN_L,PIZZA_TYPE_HAWAIIAN,L,IDR133650,IDR102951,2024-12-31 00:00:00,<NA>
2,PIZZA_PEP_MSH_PEP_L,PIZZA_TYPE_PEP_MSH_PEP,L,IDR141750,IDR111537,2024-12-31 00:00:00,<NA>
3,PIZZA_FOUR_CHEESE_L,PIZZA_TYPE_FOUR_CHEESE,L,IDR145395,IDR113724,2024-12-31 00:00:00,<NA>
4,PIZZA_FIVE_CHEESE_L,PIZZA_TYPE_FIVE_CHEESE,L,IDR149850,IDR124740,2024-12-31 00:00:00,<NA>

In [21]:
# Inisialisasi query yang akan dijalankan -> Ekstrak data mst_pizza_type
query_pizza_type = """
  SELECT
    *
  FROM fullstack-bangalore-494812.pizza_transaction.mst_pizza_type
"""

# Proses ekstraksi data dari BigQuery ke pandas
pizza_types = client.query(query_pizza_type).to_dataframe()

# Tampilkan hasil
display(pizza_types.head())

,pizza_type_id,name,category,ingredients,created_date,updated_date
0,PIZZA_TYPE_BBQ_CKN,THE BARBECUE CHICKEN PIZZA,CHICKEN,"Barbecued Chicken, Red Peppers, Green Peppers,...",2024-12-31 00:00:00,<NA>
1,PIZZA_TYPE_CALI_CKN,THE CALIFORNIA CHICKEN PIZZA,CHICKEN,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ...",2024-12-31 00:00:00,<NA>
2,PIZZA_TYPE_SOUTHW_CKN,THE SOUTHWEST CHICKEN PIZZA,CHICKEN,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja...",2024-12-31 00:00:00,<NA>
3,PIZZA_TYPE_CLASSIC_DLX,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",2024-12-31 00:00:00,<NA>
4,PIZZA_TYPE_HAWAIIAN,THE HAWAIIAN PIZZA,CLASSIC,"Sliced Ham, Pineapple, Mozzarella Cheese",2024-12-31 00:00:00,<NA>

## **Inspecting Data Information**

* Untuk dapat menginspeksi informasi umum pada data dapat menggunakan sintaks berikut

<p align="center"><code><b>DataFrame.info()</b></code></p>

<ul>Ketika dijalankan, sintaks tersebut akan menghasilkan output informasi umum pada data seperti banyak kolom, nama kolom beserta tipe data dan jumlah data tak kosong (<i>non-null value</i>)</ul><br>

<p align="right"><sup>docs : <i><a href="https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html">https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.info.html</i></sup></a></p>

### 👨‍💻 Task 3.1

Pada DataFrame yang telah dibuat pada Task 2 (orders, order_details dan pizzas), coba inspeksi semua informasi umumnya!

In [22]:
# Inspeksi informasi umum pada data
list_dataframe = {
    'orders' : orders,
    'order_details' : order_details,
    'customers' : customers,
    'pizzas' : pizzas,
    'pizza_types' : pizza_types
}

for name, data in list_dataframe.items():
    print(f'Data \033[1;33m{name}\033[0m\n')
    display(data.info())

Data orders

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21350 entries, 0 to 21349
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         21350 non-null  object
 1   customer_id      21350 non-null  object
 2   order_maker_id   21350 non-null  object
 3   order_date       21350 non-null  object
 4   order_time       21350 non-null  object
 5   completion_time  21350 non-null  object
 6   is_complain      21350 non-null  Int64
 7   complain_detail  2135 non-null   object
 8   created_date     21350 non-null  object
 9   updated_date     0 non-null      Int64
dtypes: Int64(2), object(8)
memory usage: 1.7+ MB

None

Data order_details

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48623 entries, 0 to 48622
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48619 non-null  object
 1   order_id          48623 non-null  object
 2   pizza_id          48623 non-null  object
 3   quantity          48623 non-null  Int64
 4   created_date      48623 non-null  object
 5   updated_date      0 non-null      Int64
dtypes: Int64(2), object(4)
memory usage: 2.3+ MB

None

Data customers

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 137 entries, 0 to 136
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    137 non-null    object
 1   customer_name  137 non-null    object
 2   gender         137 non-null    object
 3   birth_date     137 non-null    object
 4   phone_number   137 non-null    object
 5   email          137 non-null    object
 6   open_date      137 non-null    object
 7   created_date   137 non-null    object
 8   updated_date   0 non-null      Int64
dtypes: Int64(1), object(8)
memory usage: 9.9+ KB

None

Data pizzas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pizza_id         96 non-null     object
 1   pizza_type_id    96 non-null     object
 2   size             96 non-null     object
 3   price            96 non-null     object
 4   production_cost  96 non-null     object
 5   created_date     96 non-null     object
 6   updated_date     0 non-null      Int64
dtypes: Int64(1), object(6)
memory usage: 5.5+ KB

None

Data pizza_types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pizza_type_id  32 non-null     object
 1   name           32 non-null     object
 2   category       32 non-null     object
 3   ingredients    32 non-null     object
 4   created_date   32 non-null     object
 5   updated_date   0 non-null      Int64
dtypes: Int64(1), object(5)
memory usage: 1.7+ KB

None

<h3><i>Apakah kamu menemukan sesuatu yang janggal? Jika ya kita atur nanti ya 😊</i></h3>

# **Data Profiling**

Data profiling adalah proses menganalisis dataset untuk memahami struktur, kualitas, dan karakteristik datanya. Tujuannya biasanya untuk:
* Mengetahui tipe data tiap kolom
* Mendeteksi missing values
* Melihat distribusi data
* Menemukan outlier atau anomali
* Mengidentifikasi korelasi antar variabel

Proses ini sering jadi langkah awal sebelum analisis data atau machine learning.

docs : *https://docs.profiling.ydata.ai/latest/*

### 👨‍💻 Task 3.2

Lakukan instalasi library ydata-profiling dengan mengeksekusi perintah `pip install ydata-profiling` kemudian lakukan proses data profiling pada dataframe order_details beri judul *Profiling Report Order Details* lalu simpan hasilnya kedalam html format dan beri nama filenya `Profile Order Details.html`

In [23]:
pip install ydata-profiling

Requirement already satisfied: ydata-profiling in /usr/local/lib/python3.12/dist-packages (4.18.4)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Requirement already satisfied: visions<0.8.2,>=0.7.5 in /usr/local/lib/python3.12/dist-packages (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (0.8.1)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Requirement already satisfied: minify-html>=0.15.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.18.1)
Requirement already satisfied: filetype>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.2.0)
Requirement already satisfied: phik<0.13,>=0.12.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.12.5)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Requirement already satisfied: multimethod<2,>=1.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.12)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.1)
Requirement already satisfied: imagehash==4.3.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.3.2)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Requirement already satisfied: dacite<2,>=1.9 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.2)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.1)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.1)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.4.22)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Requirement already satisfied: puremagic in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (2.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)

In [24]:
# Import library ydata_profiling
from ydata_profiling import ProfileReport

# Lakukan profile report
profile = ProfileReport(order_details, title = 'Profiling Report Order Details')

# Simpan ke dalam file berekstensi .html
profile.to_file('Profiling Report Order Details.html')

/tmp/ipykernel_8427/1639298126.py:2: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]
 17%|█▋        | 1/6 [00:00<00:04,  1.09it/s]
100%|██████████| 6/6 [00:01<00:00,  5.10it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [26]:
profile

### 👨‍💻 Task 3.3
Hapus kolom created_date dan updated_date untuk setiap dataframe!

In [27]:
# Hapus kolom created_date dan updated_date
list_dataframe = {
    'orders' : orders,
    'order_details' : order_details,
    'customers' : customers,
    'pizzas' : pizzas,
    'pizza_types' : pizza_types
}

for _, data in list_dataframe.items():
    data.drop(columns = ['created_date', 'updated_date'], inplace = True)

## **Menggabungkan Data**

Proses atau kegiatan menyatukan data dari berbagai sumber atau tabel berdasarkan hubungan tertentu agar menjadi satu informasi utuh, dengan tujuan memudahkan analisis, pengambilan keputusan, dan pemahaman data secara menyeluruh.

Dua buah data atau lebih bisa digabungkan **asalkan memiliki kolom kunci (key) yang sama atau saling berhubungan**.

Cara menggabungkan data di pandas bisa dilakukan dengan mengeksekusi perintah berikut

```
DataFrame1.merge(DataFrame2, left_on = [key_df1], right_on = [key_df2], how)
```

<br>Dengan ketentuan :     
* **DataFrame1** adalah dataframe disebelah kiri
* **DataFrame2** adalah dataframe disebelah kanan
* **key_df1** adalah kunci pada DataFrame1 yang akan digabungkan
* **key_df2** adalah kunci pada DataFrame2 yang akan digabungkan  
* **how** adalah cara penggabungan yakni bisa ‘left’, ‘right’, ‘outer’, ‘inner’, ‘cross‘ secara default adalah ‘inner’


<br>docs : *https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html*

### 👨‍💻 Task 4.1

ERD (Entity Relationalship Diagram) pada DataFrame transaksi pizza disajikan oleh gambar berikut

<img src="https://raw.githubusercontent.com/bachtiyarma/Material/refs/heads/main/Image/Materi-SQL/ERD%20-%20Pizza.png" width="60%">

Buat DataFrame baru bernama `pizza_transaction` yang merupakan gabungan dari DataFrame yang telah dibuat sebelumnya yakni DataFrame `orders` dan `order_details`

In [37]:
# Lakukan proses penggabungan data
pizza_transaction = orders.merge(order_details, on = 'order_id', how = 'left')

# Tampilkan sampel datanya
display(pizza_transaction)

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,order_details_id,pizza_id,quantity
0,TRX000026,CUST006333,EMP000208,01/01/2025,14:54:26,15:23:02,0,None,TRXD000069,PIZZA_CLASSIC_DLX_S,1
1,TRX000026,CUST006333,EMP000208,01/01/2025,14:54:26,15:23:02,0,None,TRXD000070,PIZZA_VEGGIE_VEG_L,1
2,TRX000037,CUST003319,EMP000208,01/01/2025,16:56:09,17:18:48,0,None,TRXD000092,PIZZA_ITAL_SUPR_L,1
3,TRX000037,CUST003319,EMP000208,01/01/2025,16:56:09,17:18:48,0,None,TRXD000093,PIZZA_MEXICANA_L,1
4,TRX000057,CUST008422,EMP000208,01/01/2025,19:10:51,19:30:38,0,None,TRXD000137,PIZZA_CLASSIC_DLX_M,1
...,...,...,...,...,...,...,...,...,...,...,...
48618,TRX012098,CUST001979,EMP000756,07/21/2025,18:11:15,18:33:56,1,Wrong pizza size,TRXD027496,PIZZA_PRSC_ARGLA_S,1
48619,TRX019645,CUST001120,EMP000756,11/30/2025,17:07:35,17:34:36,1,Wrong pizza size,TRXD044710,PIZZA_BIG_MEAT_S,1
48620,TRX019645,CUST001120,EMP000756,11/30/2025,17:07:35,17:34:36,1,Wrong pizza size,TRXD044711,PIZZA_MEXICANA_L,1
48621,TRX019645,CUST001120,EMP000756,11/30/2025,17:07:35,17:34:36,1,Wrong pizza size,TRXD044712,PIZZA_PEPPR_SALAMI_M,1
48622,TRX019645,CUST001120,EMP000756,11/30/2025,17:07:35,17:34:36,1,Wrong pizza size,TRXD044713,PIZZA_SICILIAN_L,1

### 👨‍💻 Task 4.2

Kemudian hubungkan DataFrame `pizza_transaction` dengan DataFrame `customers`, `pizzas` dan `pizza_types` untuk mendapatkan informasi detail mengenai produk pizza yang terjual

In [38]:
# Lakuka proses penggabungan data
pizza_transaction =pizza_transaction.merge(customers, on='customer_id', how='left')\
                                    .merge(pizzas, on='pizza_id', how='left')\
                                    .merge(pizza_types, on='pizza_type_id', how='left')

# Tampilkan sampel datanya
display(pizza_transaction)

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,order_details_id,pizza_id,quantity,customer_name,gender,birth_date,phone_number,email,open_date,pizza_type_id,size,price,production_cost,name,category,ingredients
0,TRX000026,CUST006333,EMP000208,01/01/2025,14:54:26,15:23:02,0,None,TRXD000069,PIZZA_CLASSIC_DLX_S,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,S,IDR97200,IDR82053,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
1,TRX000026,CUST006333,EMP000208,01/01/2025,14:54:26,15:23:02,0,None,TRXD000070,PIZZA_VEGGIE_VEG_L,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_VEGGIE_VEG,L,IDR164025,IDR121905,THE VEGETABLES + VEGETABLES PIZZA,veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper..."
2,TRX000037,CUST003319,EMP000208,01/01/2025,16:56:09,17:18:48,0,None,TRXD000092,PIZZA_ITAL_SUPR_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_ITAL_SUPR,L,IDR168075,IDR149850,THE ITALIAN SUPREME PIZZA,supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
3,TRX000037,CUST003319,EMP000208,01/01/2025,16:56:09,17:18:48,0,None,TRXD000093,PIZZA_MEXICANA_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,IDR164025,IDR121014,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
4,TRX000057,CUST008422,EMP000208,01/01/2025,19:10:51,19:30:38,0,None,TRXD000137,PIZZA_CLASSIC_DLX_M,1,Nabila Nugroho,F,1978-04-09,+62 (032) 128 7819,nabila.nugroho@gmail.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,M,IDR129600,IDR92745,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48618,TRX012098,CUST001979,EMP000756,07/21/2025,18:11:15,18:33:56,1,Wrong pizza size,TRXD027496,PIZZA_PRSC_ARGLA_S,1,Jefri Sihombing,M,1982-02-26,(055) 600 5511,jefri.sihombing@gmail.com,2024/12/31,PIZZA_TYPE_PRSC_ARGLA,S,IDR101250,IDR83916,THE PROSCIUTTO AND ARUGULA PIZZA,supreme,"Prosciutto di San Daniele, Arugula, Mozzarella..."
48619,TRX019645,CUST001120,EMP000756,11/30/2025,17:07:35,17:34:36,1,Wrong pizza size,TRXD044710,PIZZA_BIG_MEAT_S,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_BIG_MEAT,S,IDR97200,IDR81567,THE BIG MEAT PIZZA,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau..."
48620,TRX019645,CUST001120,EMP000756,11/30/2025,17:07:35,17:34:36,1,Wrong pizza size,TRXD044711,PIZZA_MEXICANA_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,IDR164025,IDR121014,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
48621,TRX019645,CUST001120,EMP000756,11/30/2025,17:07:35,17:34:36,1,Wrong pizza size,TRXD044712,PIZZA_PEPPR_SALAMI_M,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_PEPPR_SALAMI,M,IDR133650,IDR103842,THE PEPPER SALAMI PIZZA,SUPREME,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ..."
48622,TRX019645,CUST001120,EMP000756,11/30/2025,17:07:35,17:34:36,1,Wrong pizza size,TRXD044713,PIZZA_SICILIAN_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_SICILIAN,L,IDR164025,IDR133650,THE SICILIAN PIZZA,SUPREME,"Coarse Sicilian Salami, Tomatoes, Green Olives..."

### 👨‍💻 Task 4.3

Lakukan inspeksi informasi umum pada DataFrame `pizza_transaction` (dataframe hasil penggabungan)

In [39]:
# Lakukan inspeksi informasi umum pada pizza_transaction
pizza_transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48623 entries, 0 to 48622
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          48623 non-null  object
 1   customer_id       48623 non-null  object
 2   order_maker_id    48623 non-null  object
 3   order_date        48623 non-null  object
 4   order_time        48623 non-null  object
 5   completion_time   48623 non-null  object
 6   is_complain       48623 non-null  Int64
 7   complain_detail   4874 non-null   object
 8   order_details_id  48619 non-null  object
 9   pizza_id          48623 non-null  object
 10  quantity          48623 non-null  Int64
 11  customer_name     48623 non-null  object
 12  gender            48623 non-null  object
 13  birth_date        48623 non-null  object
 14  phone_number      48623 non-null  object
 15  email             48623 non-null  object
 16  open_date         48623 non-null  object
 17  pizza_type_id     48623 non-null  object
 18  size              48623 non-null  object
 19  price             48623 non-null  object
 20  production_cost   48623 non-null  object
 21  name              48623 non-null  object
 22  category          48623 non-null  object
 23  ingredients       48623 non-null  object
dtypes: Int64(2), object(22)
memory usage: 9.0+ MB

## **Data Transformation**

Data transformation adalah proses mengubah data mentah ke bentuk yang lebih rapi, konsisten, dan siap digunakan untuk analisis, pelaporan, atau pemodelan.

### 👨‍💻 Task 5.1

Konversi kolom tanggal transaksi (order_date) pada `pizza_transaction` menjadi format tanggal sesuai standar (ISO 8601) yakni berformat 'YYYY-MM-DD'

<br>docs : *https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html*

Gunakan format / aturan berikut untuk membaca format data tanggal

<br>
<table border="1">
  <thead>
    <tr>
      <th>Kode Format</th>
      <th>Keterangan</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>%a</td>
      <td>Nama hari dalam bentuk singkatan sesuai lokal</td>
    </tr>
    <tr>
      <td>%A</td>
      <td>Nama hari lengkap sesuai lokal</td>
    </tr>
    <tr>
      <td>%w</td>
      <td>Hari dalam angka desimal, 0 = Minggu, 6 = Sabtu</td>
    </tr>
    <tr>
      <td>%d</td>
      <td>Tanggal dalam bulan (01–31)</td>
    </tr>
    <tr>
      <td>%b</td>
      <td>Nama bulan dalam bentuk singkatan sesuai lokal</td>
    </tr>
    <tr>
      <td>%B</td>
      <td>Nama bulan lengkap sesuai lokal</td>
    </tr>
    <tr>
      <td>%m</td>
      <td>Bulan dalam angka desimal (01–12)</td>
    </tr>
    <tr>
      <td>%y</td>
      <td>Tahun tanpa abad (00–99)</td>
    </tr>
    <tr>
      <td>%Y</td>
      <td>Tahun dengan abad (contoh: 2026)</td>
    </tr>
    <tr>
      <td>%H</td>
      <td>Jam format 24 jam (00–23)</td>
    </tr>
    <tr>
      <td>%I</td>
      <td>Jam format 12 jam (01–12)</td>
    </tr>
    <tr>
      <td>%p</td>
      <td>Penanda AM atau PM sesuai lokal</td>
    </tr>
    <tr>
      <td>%M</td>
      <td>Menit (00–59)</td>
    </tr>
    <tr>
      <td>%S</td>
      <td>Detik (00–59)</td>
    </tr>
    <tr>
      <td>%j</td>
      <td>Hari ke-dalam-tahun (001–366)</td>
    </tr>
    <tr>
      <td>%Z</td>
      <td>Nama zona waktu</td>
    </tr>
  </tbody>
</table>

<br>docs : *https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior*

In [46]:
# Konversi order_date menjadi YYYY-MM-DD
pizza_transaction['order_date'] = pd.to_datetime(pizza_transaction['order_date'], format = '%m/%d/%Y')

# Tampilkan sampel datanya
display(pizza_transaction)

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,order_details_id,pizza_id,quantity,customer_name,gender,birth_date,phone_number,email,open_date,pizza_type_id,size,price,production_cost,name,category,ingredients
0,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000069,PIZZA_CLASSIC_DLX_S,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,S,97200,IDR82053,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
1,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000070,PIZZA_VEGGIE_VEG_L,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_VEGGIE_VEG,L,164025,IDR121905,THE VEGETABLES + VEGETABLES PIZZA,veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper..."
2,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000092,PIZZA_ITAL_SUPR_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_ITAL_SUPR,L,168075,IDR149850,THE ITALIAN SUPREME PIZZA,supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
3,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000093,PIZZA_MEXICANA_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025,IDR121014,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
4,TRX000057,CUST008422,EMP000208,2025-01-01,19:10:51,19:30:38,0,None,TRXD000137,PIZZA_CLASSIC_DLX_M,1,Nabila Nugroho,F,1978-04-09,+62 (032) 128 7819,nabila.nugroho@gmail.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,M,129600,IDR92745,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48618,TRX012098,CUST001979,EMP000756,2025-07-21,18:11:15,18:33:56,1,Wrong pizza size,TRXD027496,PIZZA_PRSC_ARGLA_S,1,Jefri Sihombing,M,1982-02-26,(055) 600 5511,jefri.sihombing@gmail.com,2024/12/31,PIZZA_TYPE_PRSC_ARGLA,S,101250,IDR83916,THE PROSCIUTTO AND ARUGULA PIZZA,supreme,"Prosciutto di San Daniele, Arugula, Mozzarella..."
48619,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044710,PIZZA_BIG_MEAT_S,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_BIG_MEAT,S,97200,IDR81567,THE BIG MEAT PIZZA,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau..."
48620,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044711,PIZZA_MEXICANA_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025,IDR121014,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
48621,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044712,PIZZA_PEPPR_SALAMI_M,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_PEPPR_SALAMI,M,133650,IDR103842,THE PEPPER SALAMI PIZZA,SUPREME,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ..."
48622,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044713,PIZZA_SICILIAN_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_SICILIAN,L,164025,IDR133650,THE SICILIAN PIZZA,SUPREME,"Coarse Sicilian Salami, Tomatoes, Green Olives..."

### 👨‍💻 Task 5.2

Kolom `price`	dan `production_cost` pada DataFrame `pizza_transaction`, masih mengandung simbol Currency. Hapus simbol tersebut dan konversi tipe datanya menjadi float

<br>docs : *https://pandas.pydata.org/docs/reference/api/pandas.Series.str.replace.html*

In [48]:
pizza_transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48623 entries, 0 to 48622
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          48623 non-null  object
 1   customer_id       48623 non-null  object
 2   order_maker_id    48623 non-null  object
 3   order_date        48623 non-null  datetime64[ns]
 4   order_time        48623 non-null  object
 5   completion_time   48623 non-null  object
 6   is_complain       48623 non-null  Int64
 7   complain_detail   4874 non-null   object
 8   order_details_id  48619 non-null  object
 9   pizza_id          48623 non-null  object
 10  quantity          48623 non-null  Int64
 11  customer_name     48623 non-null  object
 12  gender            48623 non-null  object
 13  birth_date        48623 non-null  object
 14  phone_number      48623 non-null  object
 15  email             48623 non-null  object
 16  open_date         48623 non-null  object
 17  pizza_type_id     48623 non-null  object
 18  size              48623 non-null  object
 19  price             48623 non-null  int64
 20  production_cost   48623 non-null  object
 21  name              48623 non-null  object
 22  category          48623 non-null  object
 23  ingredients       48623 non-null  object
dtypes: Int64(2), datetime64[ns](1), int64(1), object(20)
memory usage: 9.0+ MB

In [53]:
# Pastikan kolom price diubah ke string dulu, hapus IDR, lalu konversi ke Float64Dtype (nullable float)
pizza_transaction['price'] = pizza_transaction['price'].astype(str).str.replace('IDR', '')
pizza_transaction['price'] = pizza_transaction['price'].astype(pd.Float64Dtype())

# Periksa hasilnya
display(pizza_transaction)
pizza_transaction.info()

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,order_details_id,pizza_id,quantity,customer_name,gender,birth_date,phone_number,email,open_date,pizza_type_id,size,price,production_cost,name,category,ingredients
0,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000069,PIZZA_CLASSIC_DLX_S,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,S,97200.0,IDR82053,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
1,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000070,PIZZA_VEGGIE_VEG_L,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_VEGGIE_VEG,L,164025.0,IDR121905,THE VEGETABLES + VEGETABLES PIZZA,veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper..."
2,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000092,PIZZA_ITAL_SUPR_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_ITAL_SUPR,L,168075.0,IDR149850,THE ITALIAN SUPREME PIZZA,supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
3,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000093,PIZZA_MEXICANA_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025.0,IDR121014,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
4,TRX000057,CUST008422,EMP000208,2025-01-01,19:10:51,19:30:38,0,None,TRXD000137,PIZZA_CLASSIC_DLX_M,1,Nabila Nugroho,F,1978-04-09,+62 (032) 128 7819,nabila.nugroho@gmail.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,M,129600.0,IDR92745,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48618,TRX012098,CUST001979,EMP000756,2025-07-21,18:11:15,18:33:56,1,Wrong pizza size,TRXD027496,PIZZA_PRSC_ARGLA_S,1,Jefri Sihombing,M,1982-02-26,(055) 600 5511,jefri.sihombing@gmail.com,2024/12/31,PIZZA_TYPE_PRSC_ARGLA,S,101250.0,IDR83916,THE PROSCIUTTO AND ARUGULA PIZZA,supreme,"Prosciutto di San Daniele, Arugula, Mozzarella..."
48619,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044710,PIZZA_BIG_MEAT_S,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_BIG_MEAT,S,97200.0,IDR81567,THE BIG MEAT PIZZA,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau..."
48620,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044711,PIZZA_MEXICANA_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025.0,IDR121014,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
48621,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044712,PIZZA_PEPPR_SALAMI_M,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_PEPPR_SALAMI,M,133650.0,IDR103842,THE PEPPER SALAMI PIZZA,SUPREME,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ..."
48622,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044713,PIZZA_SICILIAN_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_SICILIAN,L,164025.0,IDR133650,THE SICILIAN PIZZA,SUPREME,"Coarse Sicilian Salami, Tomatoes, Green Olives..."

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48623 entries, 0 to 48622
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          48623 non-null  object
 1   customer_id       48623 non-null  object
 2   order_maker_id    48623 non-null  object
 3   order_date        48623 non-null  datetime64[ns]
 4   order_time        48623 non-null  object
 5   completion_time   48623 non-null  object
 6   is_complain       48623 non-null  Int64
 7   complain_detail   4874 non-null   object
 8   order_details_id  48619 non-null  object
 9   pizza_id          48623 non-null  object
 10  quantity          48623 non-null  Int64
 11  customer_name     48623 non-null  object
 12  gender            48623 non-null  object
 13  birth_date        48623 non-null  object
 14  phone_number      48623 non-null  object
 15  email             48623 non-null  object
 16  open_date         48623 non-null  object
 17  pizza_type_id     48623 non-null  object
 18  size              48623 non-null  object
 19  price             48623 non-null  Float64
 20  production_cost   48623 non-null  object
 21  name              48623 non-null  object
 22  category          48623 non-null  object
 23  ingredients       48623 non-null  object
dtypes: Float64(1), Int64(2), datetime64[ns](1), object(20)
memory usage: 9.0+ MB

In [55]:
# Hapus simbol currency pada kolom production_cost
pizza_transaction['production_cost'] = pizza_transaction['production_cost'].str.replace('IDR', '')

# Konversi kolom production_cost menjadi float
pizza_transaction['production_cost'] = pizza_transaction['production_cost'].astype(pd.Float64Dtype())

# Periksa hasilnya
display(pizza_transaction)

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,order_details_id,pizza_id,quantity,customer_name,gender,birth_date,phone_number,email,open_date,pizza_type_id,size,price,production_cost,name,category,ingredients
0,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000069,PIZZA_CLASSIC_DLX_S,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,S,97200.0,82053.0,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
1,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000070,PIZZA_VEGGIE_VEG_L,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_VEGGIE_VEG,L,164025.0,121905.0,THE VEGETABLES + VEGETABLES PIZZA,veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper..."
2,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000092,PIZZA_ITAL_SUPR_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_ITAL_SUPR,L,168075.0,149850.0,THE ITALIAN SUPREME PIZZA,supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
3,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000093,PIZZA_MEXICANA_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025.0,121014.0,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
4,TRX000057,CUST008422,EMP000208,2025-01-01,19:10:51,19:30:38,0,None,TRXD000137,PIZZA_CLASSIC_DLX_M,1,Nabila Nugroho,F,1978-04-09,+62 (032) 128 7819,nabila.nugroho@gmail.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,M,129600.0,92745.0,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48618,TRX012098,CUST001979,EMP000756,2025-07-21,18:11:15,18:33:56,1,Wrong pizza size,TRXD027496,PIZZA_PRSC_ARGLA_S,1,Jefri Sihombing,M,1982-02-26,(055) 600 5511,jefri.sihombing@gmail.com,2024/12/31,PIZZA_TYPE_PRSC_ARGLA,S,101250.0,83916.0,THE PROSCIUTTO AND ARUGULA PIZZA,supreme,"Prosciutto di San Daniele, Arugula, Mozzarella..."
48619,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044710,PIZZA_BIG_MEAT_S,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_BIG_MEAT,S,97200.0,81567.0,THE BIG MEAT PIZZA,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau..."
48620,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044711,PIZZA_MEXICANA_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025.0,121014.0,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
48621,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044712,PIZZA_PEPPR_SALAMI_M,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_PEPPR_SALAMI,M,133650.0,103842.0,THE PEPPER SALAMI PIZZA,SUPREME,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ..."
48622,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044713,PIZZA_SICILIAN_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_SICILIAN,L,164025.0,133650.0,THE SICILIAN PIZZA,SUPREME,"Coarse Sicilian Salami, Tomatoes, Green Olives..."

### 👨‍💻 Task 5.3

Ubah nama kolom `name` menjadi `pizza_name` dan `category` menjadi `pizza_category`

<br>docs : *https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rename.html*

In [56]:
# Ubah nama kolom
pizza_transaction = pizza_transaction.rename(columns = {'name' : 'pizza_name', 'category' : 'pizza_category'})

# Periksa hasilnya
display(pizza_transaction)

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,order_details_id,pizza_id,quantity,customer_name,gender,birth_date,phone_number,email,open_date,pizza_type_id,size,price,production_cost,pizza_name,pizza_category,ingredients
0,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000069,PIZZA_CLASSIC_DLX_S,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,S,97200.0,82053.0,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
1,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000070,PIZZA_VEGGIE_VEG_L,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_VEGGIE_VEG,L,164025.0,121905.0,THE VEGETABLES + VEGETABLES PIZZA,veggie,"Mushrooms, Tomatoes, Red Peppers, Green Pepper..."
2,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000092,PIZZA_ITAL_SUPR_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_ITAL_SUPR,L,168075.0,149850.0,THE ITALIAN SUPREME PIZZA,supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni..."
3,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000093,PIZZA_MEXICANA_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025.0,121014.0,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
4,TRX000057,CUST008422,EMP000208,2025-01-01,19:10:51,19:30:38,0,None,TRXD000137,PIZZA_CLASSIC_DLX_M,1,Nabila Nugroho,F,1978-04-09,+62 (032) 128 7819,nabila.nugroho@gmail.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,M,129600.0,92745.0,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48618,TRX012098,CUST001979,EMP000756,2025-07-21,18:11:15,18:33:56,1,Wrong pizza size,TRXD027496,PIZZA_PRSC_ARGLA_S,1,Jefri Sihombing,M,1982-02-26,(055) 600 5511,jefri.sihombing@gmail.com,2024/12/31,PIZZA_TYPE_PRSC_ARGLA,S,101250.0,83916.0,THE PROSCIUTTO AND ARUGULA PIZZA,supreme,"Prosciutto di San Daniele, Arugula, Mozzarella..."
48619,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044710,PIZZA_BIG_MEAT_S,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_BIG_MEAT,S,97200.0,81567.0,THE BIG MEAT PIZZA,Classic,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau..."
48620,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044711,PIZZA_MEXICANA_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025.0,121014.0,THE MEXICANA PIZZA,veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O..."
48621,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044712,PIZZA_PEPPR_SALAMI_M,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_PEPPR_SALAMI,M,133650.0,103842.0,THE PEPPER SALAMI PIZZA,SUPREME,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ..."
48622,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044713,PIZZA_SICILIAN_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_SICILIAN,L,164025.0,133650.0,THE SICILIAN PIZZA,SUPREME,"Coarse Sicilian Salami, Tomatoes, Green Olives..."

### 👨‍💻 Task 5.4

Periksa kolom `pizza_category` dengan menyebutkan nilai *unique*-nya saja. Lakukan standarisasi penulisan data jika ditemukan data yg belum terstandarisasi!

<br>docs : *https://pandas.pydata.org/docs/reference/api/pandas.Series.unique.html*

In [59]:
# Tampilkan kolom pizza_category
display(pizza_transaction['pizza_category'])

0        CLASSIC
1         veggie
2        supreme
3         veggie
4        CLASSIC
          ...
48618    supreme
48619    Classic
48620     veggie
48621    SUPREME
48622    SUPREME
Name: pizza_category, Length: 48623, dtype: object

In [63]:
# Periksa nilai unik pada kolom pizza category
display(pizza_transaction['pizza_category'].value_counts())

pizza_category
CLASSIC    8563
veggie     7163
CHICKEN    6559
SUPREME    6123
supreme    4697
VEGGIE     4287
chicken    4256
Classic    3262
classic    2756
Supreme     957
Name: count, dtype: int64

In [64]:
# Lakukan standarisasi data pada kolom pizza_category
pizza_transaction['pizza_category'] = pizza_transaction['pizza_category'].str.upper()

# Tampilkan kolom pizza_transaction
display(pizza_transaction['pizza_category'].value_counts())

pizza_category
CLASSIC    14581
SUPREME    11777
VEGGIE     11450
CHICKEN    10815
Name: count, dtype: int64

In [65]:
# Periksa nilai unik pada kolom pizza category
display(pizza_transaction['pizza_category'].value_counts())

pizza_category
CLASSIC    14581
SUPREME    11777
VEGGIE     11450
CHICKEN    10815
Name: count, dtype: int64

## **Menambahkan Kolom Baru**

* Menambahkan kolom baru pada DataFrame berguna untuk menyimpan hasil perhitungan, transformasi, atau informasi tambahan yang berasal dari data yang sudah ada atau dari sumber lain. Untuk menambahkan kolom baru dengan operasi tertentu gunakan aturan

<p align="center"><code><b>DataFrame[nama_kolom_baru] = ...</b></code></p><br>

<ul><li>Operasi yang bisa dilakukan untuk tipe data <b>numerik</b><br></li>

<table>
<thead>
<tr>
<th>Operator / Fungsi</th>
<th>Deskripsi</th>
<th>Contoh</th>
</tr>
</thead>
<tbody>

<tr>
<td><code>+</code> atau <code>add()</code></td>
<td>Menjumlahkan nilai antar Series/DataFrame (atau dengan skalar)</td>
<td><code>s1 + s2</code> atau <code>s1.add(s2)</code></td>
</tr>

<tr>
<td><code>-</code> atau <code>sub()</code></td>
<td>Mengurangkan nilai antar Series/DataFrame (atau dengan skalar)</td>
<td><code>s1 - s2</code> atau <code>s1.sub(s2)</code></td>
</tr>

<tr>
<td><code>*</code> atau <code>mul()</code></td>
<td>Mengalikan nilai antar Series/DataFrame (atau dengan skalar)</td>
<td><code>s1 * s2</code> atau <code>s1.mul(s2)</code></td>
</tr>

<tr>
<td><code>/</code> atau <code>truediv()</code></td>
<td>Membagi nilai antar Series/DataFrame (hasil float)</td>
<td><code>s1 / s2</code> atau <code>s1.truediv(s2)</code></td>
</tr>

<tr>
<td><code>//</code> atau <code>floordiv()</code></td>
<td>Pembagian dengan pembulatan ke bawah (integer division)</td>
<td><code>s1 // s2</code> atau <code>s1.floordiv(s2)</code></td>
</tr>

<tr>
<td><code>%</code> atau <code>mod()</code></td>
<td>Mengambil sisa hasil bagi (modulus)</td>
<td><code>s1 % s2</code> atau <code>s1.mod(s2)</code></td>
</tr>

<tr>
<td><code>**</code> atau <code>pow()</code></td>
<td>Pangkat (eksponensial)</td>
<td><code>s1 ** 2</code> atau <code>s1.pow(2)</code></td>
</tr>

<tr>
<td><code>abs()</code></td>
<td>Mengambil nilai absolut</td>
<td><code>s.abs()</code></td>
</tr>

<tr>
<td><code>round(decimals=n)</code></td>
<td>Membulatkan angka ke jumlah desimal tertentu</td>
<td><code>s.round(2)</code></td>
</tr>

<tr>
<td><code>mean()</code></td>
<td>Menghitung rata-rata</td>
<td><code>s.mean()</code></td>
</tr>

<tr>
<td><code>sum()</code></td>
<td>Menjumlahkan semua nilai</td>
<td><code>s.sum()</code></td>
</tr>

<tr>
<td><code>prod()</code></td>
<td>Mengalikan semua nilai</td>
<td><code>s.prod()</code></td>
</tr>

<tr>
<td><code>min()</code> / <code>max()</code></td>
<td>Mengambil nilai minimum / maksimum</td>
<td><code>s.min()</code> / <code>s.max()</code></td>
</tr>

<tr>
<td><code>cumsum()</code></td>
<td>Menjumlahkan kumulatif</td>
<td><code>s.cumsum()</code></td>
</tr>

<tr>
<td><code>cumprod()</code></td>
<td>Perkalian kumulatif</td>
<td><code>s.cumprod()</code></td>
</tr>

<tr>
<td><code>diff(periods=n)</code></td>
<td>Selisih antar elemen (default 1 baris)</td>
<td><code>s.diff()</code></td>
</tr>

<tr>
<td><code>pct_change()</code></td>
<td>Menghitung persentase perubahan antar nilai</td>
<td><code>s.pct_change()</code></td>
</tr>

<tr>
<td><code>clip(lower, upper)</code></td>
<td>Memotong nilai di luar rentang tertentu</td>
<td><code>s.clip(0, 100)</code></td>
</tr>

<tr>
<td><code>add(other, fill_value=0)</code></td>
<td>Menjumlahkan sambil mengganti nilai NaN dengan default</td>
<td><code>s1.add(s2, fill_value=0)</code></td>
</tr>

</tbody>
</table>
</ul>
<br>
<ul><li>Operasi yang bisa dilakukan untuk tipe data <b>string</b><br></li>
<table>
<thead>
<tr>
<th>Fungsi</th>
<th>Deskripsi</th>
<th>Contoh</th>
</tr>
</thead>
<tbody>

<tr>
<td><code>str.lower()</code></td>
<td>Mengubah semua huruf menjadi huruf kecil</td>
<td><code>s.str.lower()</code> → <code>'abc'</code></td>
</tr>

<tr>
<td><code>str.upper()</code></td>
<td>Mengubah semua huruf menjadi huruf besar</td>
<td><code>s.str.upper()</code> → <code>'ABC'</code></td>
</tr>

<tr>
<td><code>str.title()</code></td>
<td>Mengubah huruf pertama tiap kata menjadi kapital</td>
<td><code>'hello world'</code> → <code>'Hello World'</code></td>
</tr>

<tr>
<td><code>str.strip()</code></td>
<td>Menghapus spasi di awal dan akhir string</td>
<td><code>'  data '</code> → <code>'data'</code></td>
</tr>

<tr>
<td><code>str.replace(pat, repl)</code></td>
<td>Mengganti teks dengan teks lain</td>
<td><code>s.str.replace('a', 'o')</code></td>
</tr>

<tr>
<td><code>str.contains(pat)</code></td>
<td>Memeriksa apakah string mengandung pola tertentu (regex)</td>
<td><code>s.str.contains('abc')</code></td>
</tr>

<tr>
<td><code>str.startswith(pat)</code></td>
<td>Memeriksa apakah string diawali pola tertentu</td>
<td><code>s.str.startswith('A')</code></td>
</tr>

<tr>
<td><code>str.endswith(pat)</code></td>
<td>Memeriksa apakah string diakhiri pola tertentu</td>
<td><code>s.str.endswith('.com')</code></td>
</tr>

<tr>
<td><code>str.len()</code></td>
<td>Menghitung panjang tiap string</td>
<td><code>s.str.len()</code> → <code>[5, 3, 7]</code></td>
</tr>

<tr>
<td><code>str.split(pat)</code></td>
<td>Memisahkan string berdasarkan delimiter</td>
<td><code>'a,b,c'</code> → <code>['a','b','c']</code></td>
</tr>

<tr>
<td><code>str.cat(sep=' ')</code></td>
<td>Menggabungkan string dengan pemisah tertentu</td>
<td><code>s.str.cat(sep=' ')</code></td>
</tr>

<tr>
<td><code>str.extract(pat)</code></td>
<td>Menangkap pola dengan regex dan hasilkan kolom baru</td>
<td><code>s.str.extract(r'(\d+)')</code></td>
</tr>

<tr>
<td><code>str.findall(pat)</code></td>
<td>Menemukan semua kecocokan pola (regex) di setiap elemen</td>
<td><code>s.str.findall(r'\d+')</code></td>
</tr>

<tr>
<td><code>str.zfill(width)</code></td>
<td>Menambahkan nol di depan hingga panjang tertentu</td>
<td><code>'42'</code> → <code>'00042'</code></td>
</tr>

<tr>
<td><code>str.pad(width, fillchar=' ')</code></td>
<td>Menambahkan karakter tertentu di kiri/kanan</td>
<td><code>'A'</code> → <code>'  A  '</code></td>
</tr>

<tr>
<td><code>str.get(i)</code></td>
<td>Mengambil elemen indeks ke-i dari list/string</td>
<td><code>s.str.get(0)</code></td>
</tr>

<tr>
<td><code>str.join(sep)</code></td>
<td>Menggabungkan elemen list menjadi string</td>
<td><code>s.str.join('-')</code> → <code>'a-b-c'</code></td>
</tr>

<tr>
<td><code>str.replace(rgx, repl, regex=True)</code></td>
<td>Mengganti teks menggunakan ekspresi reguler</td>
<td><code>s.str.replace(r'\d+', '', regex=True)</code></td>
</tr>

<tr>
<td><code>str.wrap(width)</code></td>
<td>Membungkus teks menjadi beberapa baris</td>
<td><code>s.str.wrap(10)</code></td>
</tr>

<tr>
<td><code>str.normalize('NFKD')</code></td>
<td>Menormalkan karakter Unicode</td>
<td><code>s.str.normalize('NFKD')</code></td>
</tr>

</tbody>
</table>
</ul>

### 👨‍💻 Task 6.1

Tambahkan kolom `total_price` yang merupakan hasil perkalian dari kolom `quantity` dan `price`

In [66]:
# Buat kolom baru total_price hasil perhitungan
pizza_transaction['total_price'] = pizza_transaction['quantity'] * pizza_transaction['price']

# Tampilkan datanya
display(pizza_transaction)

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,order_details_id,pizza_id,quantity,customer_name,gender,birth_date,phone_number,email,open_date,pizza_type_id,size,price,production_cost,pizza_name,pizza_category,ingredients,total_price
0,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000069,PIZZA_CLASSIC_DLX_S,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,S,97200.0,82053.0,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",97200.0
1,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000070,PIZZA_VEGGIE_VEG_L,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_VEGGIE_VEG,L,164025.0,121905.0,THE VEGETABLES + VEGETABLES PIZZA,VEGGIE,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",164025.0
2,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000092,PIZZA_ITAL_SUPR_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_ITAL_SUPR,L,168075.0,149850.0,THE ITALIAN SUPREME PIZZA,SUPREME,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",168075.0
3,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000093,PIZZA_MEXICANA_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025.0,121014.0,THE MEXICANA PIZZA,VEGGIE,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",164025.0
4,TRX000057,CUST008422,EMP000208,2025-01-01,19:10:51,19:30:38,0,None,TRXD000137,PIZZA_CLASSIC_DLX_M,1,Nabila Nugroho,F,1978-04-09,+62 (032) 128 7819,nabila.nugroho@gmail.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,M,129600.0,92745.0,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",129600.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48618,TRX012098,CUST001979,EMP000756,2025-07-21,18:11:15,18:33:56,1,Wrong pizza size,TRXD027496,PIZZA_PRSC_ARGLA_S,1,Jefri Sihombing,M,1982-02-26,(055) 600 5511,jefri.sihombing@gmail.com,2024/12/31,PIZZA_TYPE_PRSC_ARGLA,S,101250.0,83916.0,THE PROSCIUTTO AND ARUGULA PIZZA,SUPREME,"Prosciutto di San Daniele, Arugula, Mozzarella...",101250.0
48619,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044710,PIZZA_BIG_MEAT_S,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_BIG_MEAT,S,97200.0,81567.0,THE BIG MEAT PIZZA,CLASSIC,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau...",97200.0
48620,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044711,PIZZA_MEXICANA_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025.0,121014.0,THE MEXICANA PIZZA,VEGGIE,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",164025.0
48621,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044712,PIZZA_PEPPR_SALAMI_M,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_PEPPR_SALAMI,M,133650.0,103842.0,THE PEPPER SALAMI PIZZA,SUPREME,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ...",133650.0
48622,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044713,PIZZA_SICILIAN_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_SICILIAN,L,164025.0,133650.0,THE SICILIAN PIZZA,SUPREME,"Coarse Sicilian Salami, Tomatoes, Green Olives...",164025.0

### 👨‍💻 Task 6.2

Tambahkan kolom `total_profit` yang merupakan hasil perkalian dari kolom `quantity` dan selisih antara `price` dan `production_cost`

In [67]:
# Buat kolom baru total_price hasil perhitungan
pizza_transaction['total_profit'] = pizza_transaction['quantity'] * (pizza_transaction['price'] - pizza_transaction['production_cost'])

# Tampilkan datanya
display(pizza_transaction)

,order_id,customer_id,order_maker_id,order_date,order_time,completion_time,is_complain,complain_detail,order_details_id,pizza_id,quantity,customer_name,gender,birth_date,phone_number,email,open_date,pizza_type_id,size,price,production_cost,pizza_name,pizza_category,ingredients,total_price,total_profit
0,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000069,PIZZA_CLASSIC_DLX_S,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,S,97200.0,82053.0,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",97200.0,15147.0
1,TRX000026,CUST006333,EMP000208,2025-01-01,14:54:26,15:23:02,0,None,TRXD000070,PIZZA_VEGGIE_VEG_L,1,Darijan Nainggolan,M,1985-12-23,+62 (448) 155 7771,darijan.nainggolan@yahoo.com,2024/12/31,PIZZA_TYPE_VEGGIE_VEG,L,164025.0,121905.0,THE VEGETABLES + VEGETABLES PIZZA,VEGGIE,"Mushrooms, Tomatoes, Red Peppers, Green Pepper...",164025.0,42120.0
2,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000092,PIZZA_ITAL_SUPR_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_ITAL_SUPR,L,168075.0,149850.0,THE ITALIAN SUPREME PIZZA,SUPREME,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",168075.0,18225.0
3,TRX000037,CUST003319,EMP000208,2025-01-01,16:56:09,17:18:48,0,None,TRXD000093,PIZZA_MEXICANA_L,1,Cornelia Wijayanti,F,1997-03-05,(033) 657-9634,cornelia.wijayanti@gmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025.0,121014.0,THE MEXICANA PIZZA,VEGGIE,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",164025.0,43011.0
4,TRX000057,CUST008422,EMP000208,2025-01-01,19:10:51,19:30:38,0,None,TRXD000137,PIZZA_CLASSIC_DLX_M,1,Nabila Nugroho,F,1978-04-09,+62 (032) 128 7819,nabila.nugroho@gmail.com,2024/12/31,PIZZA_TYPE_CLASSIC_DLX,M,129600.0,92745.0,THE CLASSIC DELUXE PIZZA,CLASSIC,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",129600.0,36855.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48618,TRX012098,CUST001979,EMP000756,2025-07-21,18:11:15,18:33:56,1,Wrong pizza size,TRXD027496,PIZZA_PRSC_ARGLA_S,1,Jefri Sihombing,M,1982-02-26,(055) 600 5511,jefri.sihombing@gmail.com,2024/12/31,PIZZA_TYPE_PRSC_ARGLA,S,101250.0,83916.0,THE PROSCIUTTO AND ARUGULA PIZZA,SUPREME,"Prosciutto di San Daniele, Arugula, Mozzarella...",101250.0,17334.0
48619,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044710,PIZZA_BIG_MEAT_S,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_BIG_MEAT,S,97200.0,81567.0,THE BIG MEAT PIZZA,CLASSIC,"Bacon, Pepperoni, Italian Sausage, Chorizo Sau...",97200.0,15633.0
48620,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044711,PIZZA_MEXICANA_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_MEXICANA,L,164025.0,121014.0,THE MEXICANA PIZZA,VEGGIE,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",164025.0,43011.0
48621,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044712,PIZZA_PEPPR_SALAMI_M,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_PEPPR_SALAMI,M,133650.0,103842.0,THE PEPPER SALAMI PIZZA,SUPREME,"Genoa Salami, Capocollo, Pepperoni, Tomatoes, ...",133650.0,29808.0
48622,TRX019645,CUST001120,EMP000756,2025-11-30,17:07:35,17:34:36,1,Wrong pizza size,TRXD044713,PIZZA_SICILIAN_L,1,Kawaca Wastuti,M,1994-03-20,+62 (630) 685-6130,kawaca.wastuti@hotmail.com,2024/12/31,PIZZA_TYPE_SICILIAN,L,164025.0,133650.0,THE SICILIAN PIZZA,SUPREME,"Coarse Sicilian Salami, Tomatoes, Green Olives...",164025.0,30375.0

##**Aggregation**

Agregasi data merupakan serangkaian proses yang dilakukan untuk melakukan pengumpulan data dan dinyatakan dalam bentuk ringkasan sebagai contoh menghitung total yang dikelompokkan berdasarkan kategori tertentu, dsb.

Untuk melakukan agregasi gunakan sintaks berikut

<p align="center"><code><b>DataFrame.groupby(by, as_index).agg(kolom_hasil_aggregasi = (kolom_dihitung, jenis_agregasi))</b></code></p>

Jenis agregasi :
* sum = Menghitung total data
* mean = Menghitung rataan data
* max = Menghitung nilai maksimum data
* min = Menghitung nilai minimum data
* nunique = Menghitung jumlah data unik data
* count = Menghitung banyak data

<br>docs : *https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.groupby.html*

### 👨‍💻 Task 7

Pada DataFrame `pizza_transaction`, lakukan perhitungan :      
* Total kuantitas
* Total amount (price)
* Total profit
* Total komplain

untuk setiap harinya pada kategori dan nama pizza terjual. Simpan hasil perhitungan kedalam dataframe `result`

In [68]:
# Lakukan perhitungan agregasi
result = pizza_transaction.groupby(by = ['order_date', 'pizza_name', 'pizza_category'], as_index = False).agg(
    total_kuantitas = ('quantity', 'sum'),
    total_amount = ('total_price', 'sum'),
    total_profit = ('total_profit', 'sum'),
    total_complain = ('is_complain', 'sum')
)

# Tampilkan hasilnya
display(result)

,order_date,pizza_name,pizza_category,total_kuantitas,total_amount,total_profit,total_complain
0,2025-01-01,THE BARBECUE CHICKEN PIZZA,CHICKEN,11,1654425.0,380052.0,2
1,2025-01-01,THE BIG MEAT PIZZA,CLASSIC,5,486000.0,78165.0,1
2,2025-01-01,THE CALABRESE PIZZA,SUPREME,1,131625.0,16605.0,1
3,2025-01-01,THE CALIFORNIA CHICKEN PIZZA,CHICKEN,4,575100.0,153171.0,0
4,2025-01-01,THE CHICKEN ALFREDO PIZZA,CHICKEN,2,238950.0,50220.0,0
...,...,...,...,...,...,...,...
11028,2025-12-31,THE SPINACH AND FETA PIZZA,VEGGIE,5,585225.0,89505.0,2
11029,2025-12-31,THE SPINACH PESTO PIZZA,VEGGIE,5,672300.0,93798.0,0
11030,2025-12-31,THE SPINACH SUPREME PIZZA,SUPREME,2,267300.0,36612.0,1
11031,2025-12-31,THE THAI CHICKEN PIZZA,CHICKEN,3,439425.0,66663.0,2
11032,2025-12-31,THE VEGETABLES + VEGETABLES PIZZA,VEGGIE,10,1304100.0,354456.0,1

##**Save Your Result**

Simpan data yang sudah dihitung ke dalam media penyimpanan (seperti file atau database) agar dapat digunakan kembali tanpa harus menghitung ulang.

Hal ini penting karena memastikan hasil analisis tidak hilang, memudahkan pelacakan dan verifikasi data, mempercepat proses kerja selanjutnya, serta memungkinkan data dibagikan atau diarsipkan sebagai bukti dan referensi.

<table border="1" cellpadding="6" cellspacing="0"> <thead> <tr> <th>Fungsi</th> <th>Format File</th> <th>Contoh Kode</th> <th>Kegunaan</th> </tr> </thead> <tbody> <tr> <td><code>to_csv()</code></td> <td>CSV (.csv)</td> <td><code>df.to_csv("data.csv", index=False)</code></td> <td>Menyimpan data tabular ringan, mudah dibuka di Excel &amp; text editor</td> </tr> <tr> <td><code>to_excel()</code></td> <td>Excel (.xlsx)</td> <td><code>df.to_excel("data.xlsx", index=False)</code></td> <td>Menyimpan data ke Excel dengan format tabel</td> </tr> <tr> <td><code>to_json()</code></td> <td>JSON (.json)</td> <td><code>df.to_json("data.json", orient="records")</code></td> <td>Pertukaran data antar sistem / API</td> </tr> <tr> <td><code>to_html()</code></td> <td>HTML (.html)</td> <td><code>df.to_html("data.html", index=False)</code></td> <td>Menampilkan tabel di web / laporan</td> </tr> <tr> <td><code>to_parquet()</code></td> <td>Parquet (.parquet)</td> <td><code>df.to_parquet("data.parquet")</code></td> <td>Format cepat &amp; efisien untuk big data</td> </tr> <tr> <td><code>to_pickle()</code></td> <td>Pickle (.pkl)</td> <td><code>df.to_pickle("data.pkl")</code></td> <td>Menyimpan objek pandas lengkap (internal)</td> </tr> <tr> <td><code>to_sql()</code></td> <td>Database (SQL)</td> <td><code>df.to_sql("tabel", conn, if_exists="replace")</code></td> <td>Menyimpan data ke database (MySQL, PostgreSQL, SQLite)</td> </tr> <tr> <td><code>to_clipboard()</code></td> <td>Clipboard</td> <td><code>df.to_clipboard(index=False)</code></td> <td>Copy data langsung ke Excel / Sheets</td> </tr> </tbody> </table>

### 👨‍💻 Task 8.1

Simpan DataFrame hasil transformasi data `pizza_transaction` kedalam sebuah file berekstensi '.csv'. Beri nama filenya `pizza_transaction.csv`

docs : *https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html*

In [70]:
# Simpan pizza_transaction hasil perhitungan ke Pizza Transaction.csv
pizza_transaction.to_csv('pizza_transaction.csv', index = False)

### 👨‍💻 Task 8.2

Simpan DataFrame hasil agregasi data `result` kedalam sebuah file berekstensi '.csv'. Beri nama filenya `pizza_transaction_agg.csv`

docs : *https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html*

In [69]:
# Simpan result hasil perhitungan ke Pizza Transaction Summary.cs
result.to_csv('pizza_trx_result.csv', index = False)

Data Source : <i>https://mavenanalytics.io/data-playground/pizza-place-sales</i> (dengan modifikasi)

---

<br>
<img src="https://img.shields.io/badge/-© 2026 | Data Engineer Course FSB-417DAC?style=for-the-badge&logoColor=white"/>

<br><img src="https://fullstackbangalore.com/wp-content/uploads/2025/12/Logo-Fullstack-Bangalore.webp">